### ISSUE TITLE
Add cml_image_definition for NSO and Netbox

### ISSUE THREAD

**Issue by jasonking3** [model-driven-devops/mdd#17]
To make the mdd repo portable, we should define the NSO and Netbox image definitions in `group_vars/all/local.yml`.  Otherwise the build will most likely fail, unless the image definition IDs on the target CML server happen to line up with what is in the CML lab file (unlikely).

**Comment by stevenca** [comment]
OBE.   I am handing this with Ansible to setup these things on top of the Ubuntu image.
