### ISSUE TITLE
NSO Files not accessible HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by henne49** [model-driven-devops/mdd#90]
Hi, 

I'm unable to pull the NSO Files from aws s3 bucket in inventory/nso.yml 

Can you help me to pull them correctly off?

nso_installer_file: https://colabucket.s3.amazonaws.com/sw/cisco/nso/5.7.7/nso-5.7.7.linux.x86_64.signed.bin
    nso_ned_files:
      - https://colabucket.s3.amazonaws.com/sw/cisco/nso/5.7.7/ncs-5.7.7-cisco-ios-6.87.signed.bin
      - https://colabucket.s3.amazonaws.com/sw/cisco/nso/5.7.7/ncs-5.7.7-cisco-nx-5.23.5.signed.bin
      - https://colabucket.s3.amazonaws.com/sw/cisco/nso/5.7.7/ncs-5.7.7-cisco-iosxr-7.43.3.signed.bin
      - https://colabucket.s3.amazonaws.com/sw/cisco/nso/5.7.7/ncs-5.7.7-cisco-asa-6.16.2.signed.bin
    nso_default_ned: cisco-ios-cli-6.87

**Comment by jasonking3** [comment]
These files are not published to the public.  However, developer versions can be downloaded from here:  https://developer.cisco.com/site/nso/
